name: "Get Reports"
on:
  schedule:
    - cron: '*/40 * * * *'
  push:
    branches:
      - main

jobs:
  update-data:
    name: Update Reports
    runs-on: ubuntu-20.04
    permissions:
      contents: write
    env:
      GITHUB_PAT: ${{ secrets.GITHUB_TOKEN }}
      GOOGLE_APPLICATION_KEY: ${{ secrets.GOOGLE_APPLICATION_KEY }}
    steps:
      - name: Setup R
        uses: r-lib/actions/setup-r@v2
        with:
          r-version: 'release'
      - name: Setup - Checkout repo
        uses: actions/checkout@v3
      - name: Apt-get needed things
        run: |
          sudo apt-get install --no-install-recommends -y \
          libssl-dev \
          libcurl4-openssl-dev \
          libxml2-dev \
          libharfbuzz-dev \
          libfribidi-dev
      - run: echo "🍏 This job's status is ${{ job.status }}."
      - name: Setup Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '16.x'  # Choose the appropriate Node.js version

      - name: Install dependencies
        run: npm ci
      - name: Install playwright browsers
        run: npx playwright install --with-deps
      - name: "Check Playwright CLI"
        run: npx playwright --version

      - name: "Install Packages"
        run: |
          install.packages('pacman')
          install.packages('remotes')
          install.packages('dplyr')
          install.packages('tibble')
          install.packages('xml2')
          install.packages('rvest')
          install.packages('reticulate')
          install.packages('purrr')
          pacman::p_load(reticulate, fs, progress, tidyr, countrycode, dplyr, stringr, lubridate, purrr, glue, rvest, cli, digest)
          remotes::install_github("benjaminguinaudeau/playwrightr", force = T)
        shell: Rscript {0}
      - name: Pull Latest Changes
        run: git pull origin main
      - name: "Script - Run"
        run: Rscript 'get.R'


      - name: "Commit"
        uses: stefanzweifel/git-auto-commit-action@v4
        with:
          commit_message: Script Routine Thirty
      - name: Trigger another workflow
        run: |
          curl -X POST \
            -H "Authorization: token ${{ secrets.GITHUB_TOKEN }}" \
            -H "Accept: application/vnd.github.v3+json" \
            "https://api.github.com/repos/favstats/meta_reports2/actions/workflows/save/dispatches" \
            -d '{"ref":"main"}'
