name: "Save Files"
on:
  push:
    branches:
      - main

jobs:
  save-data:
    name: Save Reports
    runs-on: ubuntu-20.04
    permissions:
      contents: write
    env:
      GITHUB_PAT: ${{ secrets.GITHUB_TOKEN }}
    steps:
      - name: Setup R
        uses: r-lib/actions/setup-r@v2
        with:
          r-version: 'release'
      - name: Setup - Checkout repo
        uses: actions/checkout@v3
      - name: Apt-get needed things
        run: |
          sudo apt-get install --no-install-recommends -y \
          libssl-dev \
          libcurl4-openssl-dev \
          libxml2-dev \
          libharfbuzz-dev \
          libfribidi-dev
      - run: echo "🍏 This job's status is ${{ job.status }}."
      - name: "Install Packages"
        run: |
          install.packages('pacman')
          install.packages('remotes')
          install.packages('dplyr')
          install.packages('tibble')
          install.packages('xml2')
          install.packages('rvest')
          install.packages('reticulate')
          install.packages('purrr')
          pacman::p_load(reticulate, fs, progress, tidyr, countrycode, dplyr, stringr, lubridate, purrr, glue, rvest, cli, digest)
        shell: Rscript {0}
      - name: "Script - Run"
        run: Rscript 'save.R'


      - name: "Commit"
        uses: stefanzweifel/git-auto-commit-action@v4
        with:
          commit_message: Script Routine Thirty
